parameters:
    netgen_more.generator.available_environments: [ dev, prod ]
    netgen_more.generator.defaults.admin_siteaccess_name: administration
    netgen_more.generator.defaults.domain_suffix: netgen.biz
